#!/bin/sh
# This is an example script to be used as pre-commit hook.
# It builds a ZIP archive with your DNS settings and submit it for validation.
#
# 1. You must replace the USERNAME and PASSWORD variables.
# 2. Enable pre-commit hook by setting hooks directory to .githooks:
#    git config core.hooksPath .githooks
#
# Restore default settings:
#    git config --unset core.hooksPath

set -euf -o pipefail

USERNAME="user@example.com"   # change me
PASSWORD="__LUADNS_API_KEY__" # change me
ARCHIVE=$(mktemp /tmp/archive-XXXX).zip

cleanup_on_exit() {
  rm -f $ARCHIVE
}
trap cleanup_on_exit EXIT

echo "===> Creating ${ARCHIVE} archive ..."
zip -r --quiet $ARCHIVE $(git ls-files)

echo "===> Checking ${ARCHIVE} archive ..."
curl --silent --user "${USERNAME}:${PASSWORD}" \
      --json '{"file" : "'"$(base64 -w 0 < $ARCHIVE)"'"}' \
      --request POST https://api.luadns.com/v1/githooks/pre-commit \
      | jq
