-- File: example.com.lua
-- Zone: example.com
-- _a = "example.com"

-- The build system exports a variable name `_a` with zone name as value.
-- The `_a` variable is useful to build the content part of the record
-- with `concat` function or .. string concatenation operator.
-- For the name part of the record it's recommended to use relative names.

-- The SOA record is automatically generated by the build system,
-- the serial is incremented after each zone update. Currently serial
-- represents unix time of the modification.

-- The default NS records are automatically injected by the build system:
--
-- ns("", "ns1.luadns.net", 86400)
-- ns("", "ns1.luadns.net", 86400)
-- ns("", "ns1.luadns.net", 86400)
-- ns("", "ns1.luadns.net", 86400)
--
-- Only paid packages can customize their name servers, see vanity name
-- servers, see: https://www.luadns.com/help.html#vanity-name-servers

local vps_ip4 = "185.142.218.10"
local vps_ip6 = "2001:67c:25a0::10"
local app     = "myapp.herokudns.com"

-- A records
-- example.com A 185.142.218.10
-- vpn.example.com A 2001:67c:25a0::10
a("", vps_ip4)
a("vpn", vps_ip4)

-- AAAA records
-- example.com AAAA 2001:67c:25a0::10
-- vpn.example.com AAAA 2001:67c:25a0::10
aaaa("", vps_ip6)
aaaa("vpn", vps_ip6)

-- CNAME records
-- www.example.com CNAME example.com
cname("www", app)

-- Add CAA records for Let's Encrypt certificates and report unauthorized
-- attempts to issue SSL/TLS certificates via email to joe@example.com.
caa("", "letsencrypt.org", "issue")
caa("", "mailto:joe@example.com", "iodef")

-- ALIAS records
-- The app.example.com will resolve to myapp.herokudns.com IP addresses.
-- The system periodically will resolve myapp.herokudns.comm and will sync
-- A and AAAA records for app.example.com.
alias("app", app)

-- Apply a custom templates, from the 'templates' directory
google_workspace(_a)

-- Configure SPF record
txt("", "v=spf1 a mx include:_spf.google.com ~all")

-- When changing DNS settings we want to keep some records between builds.
-- Ignore DNS-01 challenge records created by Let's Encrypt.
ignore("_acme-challenge.%", "TXT")

-- Add two secondary name servers
-- The `slave` function will insert NS records and will configure AXFR & NOTIFY with supplied IP address.
-- The secondary name servers should be configured with `axfr.luadns.net` as primary server.
slave("a.ns.example.com", "10.10.10.1")
slave("b.ns.example.com", "10.10.10.2")
